### ISSUE TITLE
Update README file contribution section with information on how to contribute

### ISSUE THREAD

**Issue by victormarante** [ModernRonin/FluentArgumentParser#31]

**Comment by victormarante** [comment]
#30 PR with updates.

**Comment by ModernRonin** [comment]
I assigned this to you - I think you can close it already, but maybe you still want to do something, so I leave that up to you.

**Comment by victormarante** [comment]
> I assigned this to you, @victormarante - I think you can close it already, but maybe you still want to do something, so I leave that up to you.

Hi. We can close this issue if you feel satisfied with the changes I made.
