### ISSUE TITLE
Handle localization and culture info for numerical values for unit tests

### ISSUE THREAD

**Issue by victormarante** [ModernRonin/FluentArgumentParser#33]
Some unit tests asserts on hard-coded floating point values that use period as delimiter. Some cultures use comma (I assume there are other delimiters).

**Comment by ModernRonin** [comment]
good point. 
there is an NUnit attribute to set the culture for a test: `[SetCulture("fr-FR")]`.
we could uses this to set invariant culture.

**Comment by victormarante** [comment]
Yes, that would solve the issue. If it's only for tests, I think hard-coding to a decided culture is good enough.

**Comment by ModernRonin** [comment]
I think we can close this, you had a PR for this that's already merged, or am I mistaken?

**Comment by victormarante** [comment]
Yes, this was merged. So we can close this one.
